name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      GIT_SUBMODULE_STRATEGY: recursive
      CONAN_HOME: ${{ github.workspace }}/.conan2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up cache for Conan
        uses: actions/cache@v3
        with:
          path: .conan2
          key: conan-${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}
          restore-keys: |
            conan-${{ runner.os }}-

      - name: Install development tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake git ninja-build pkgconf python3-pip
          pip install conan --break-system-packages

      - name: Install project dependencies
        run: |
          sudo apt-get install -y libvulkan-dev libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libxau-dev libxaw7-dev libegl-dev xkb-data libxcomposite-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmuu-dev libxrandr-dev libxrender-dev libxres-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-ewmh-dev libxcb-res0-dev libxcb-composite0 libxcb-composite0-dev libxcursor-dev libxcursor1 libxkbfile-dev libxkbfile1 libxss-dev libxss1 uuid-dev libxcb-util-dev

      - name: Set up Conan profile
        run: |
          conan profile detect -e
          conan config install --args="-b mikage" https://github.com/mikage-emu/conan-3ds.git
          conan setup-3ds

      - name: Install Conan dependencies
        run: |
          conan install . --build=missing -c tools.system.package_manager:mode=install
          conan cache clean

      - name: Build project
        run: |
          mkdir build && cd build
          conan install .. -of .
          cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install -DCMAKE_PREFIX_PATH=${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_COLOR_DIAGNOSTICS=ON
          ninja
